name: 'pytest单元测试'                                                         # 插件名称
description: '使用pytest框架自动下载代码并进行单元测试'                         # 插件描述
inputs:                                                                        # 插件输入定义, 类比我们的低代码界面
  python_version:                                                              # 输入参数名称     
    description: 'pyton版本'                                                   # 输出参数描述
    required: true                                                             # 是否必填
    default: 3.8                                                               # 默认值

outputs:                                                                       
  test:
    description: "test output"
    value: ${{ steps.make-output.outputs.test }}

runs:
  using: "composite"
  steps:
    - name: '代码下载'
      uses: actions/checkout@v3
      
    - name: 'python安装'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        
    - name: '依赖库安装'
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.3.1
        pip install pytest-json-report==1.5.0
        pip install -r requirements.txt        
      shell: bash
        
    - name: '运行单元测试'
      run: pytest --json-report
      shell: bash
      
    - name: '上传产物'
      uses: actions/upload-artifact@v3
      with:
        name: '测试报告'
        path: .report.json
    
    - id: make-output
      name: '变量输出'
      run: echo "test=hello" >> $GITHUB_OUTPUT
      shell: bash
