name: 'pytest单元测试'
description: '使用pytest框架自动下载代码并进行单元测试'
inputs:
  python_version:
    description: 'pyton版本'
    required: true
    default: 3.8

runs:
  using: "composite"
  steps:
    - name: '代码下载'
      uses: actions/checkout@v3
      
    - name: 'python安装'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        
    - name: '依赖库安装'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: '运行单元测试'
      run: pytest
